
[kdp_match_name.en#]
description = "Template for any supported network based protocol"
[kdp_match_name.firewire]
description = "Serial debug across a classical firewire (or TBT to Firewire adapter)"
[kdp_match_name.mojo1]
description = "Mojo1 - internal serial debug protocol"
[kdp_match_name.mojo2]
description = "Mojo2 - internal serial debug protocol"