
[commands.LC_BUILD_VERSION]
description = "Contains information about the binaries platform, it's target and minimum SDK"
value = 50
[commands.LC_CODE_SIGNATURE]
description = "Section of mach-o that contains a signature for the object"
value = 29
[commands.LC_DATA_IN_CODE]
description = "Generic region of a Mach-O file that can contain arbitrary data"
value = 41
[commands.LC_DYLD_CHAINED_FIXUPS]
value = 2147483700
[commands.LC_DYLD_ENVIRONMENT]
value = 39
[commands.LC_DYLD_EXPORTS_TRIE]
description = "The exporeted DYLD symbols from this dylib"
value = 2147483699
[commands.LC_DYLD_INFO]
value = 34
[commands.LC_DYLD_INFO_ONLY]
value = 2147483682
[commands.LC_DYLIB_CODE_SIGN_DRS]
description = "Classical code signing \"designated requirements\".  No longer in common usage as this is now in a LC_CODE_SIGNATURE \"magic page\""
value = 43
[commands.LC_DYSYMTAB]
description = "Dynamic or indirect symbol table."
value = 11
[commands.LC_ENCRYPTION_INFO]
description = "Used by FairPlay / DSMOS to protect a binary from dump / reverse engineering (DRM, be mindful of DMCA)"
value = 33
[commands.LC_ENCRYPTION_INFO_64]
description = "Used by FairPlay / DSMOS to protect a binary from dump / reverse engineering (DRM, be mindful of DMCA)"
value = 44
[commands.LC_FILESET_ENTRY]
description = "An entry of a Mach-O object containing other Mach-O files.  Current usage is in macOS 11+ KernelCollections"
value = 2147483701
[commands.LC_FUNCTION_STARTS]
value = 38
[commands.LC_FVMFILE]
value = 9
[commands.LC_IDENT]
description = "Identity of this Mach-O object"
value = 8
[commands.LC_IDFVMLIB]
value = 7
[commands.LC_ID_DYLIB]
description = "Unique identifier for this dynamic library to be used in locating it for import"
value = 13
[commands.LC_ID_DYLINKER]
description = "The identity of the dynamic linker (dyld) expected to be used to bind this object in memory"
value = 15
[commands.LC_LAZY_LOAD_DYLIB]
description = "Dylibs that should be included in this objects dependencies but should only be loaded and bound when a reference is made to them"
value = 32
[commands.LC_LINKER_OPTIMIZATION_HINT]
value = 46
[commands.LC_LINKER_OPTION]
value = 45
[commands.LC_LOADFVMLIB]
value = 6
[commands.LC_LOAD_DYLIB]
description = "Load a dynamic library (dylib) by it's identity.  This occurs before process start."
value = 12
[commands.LC_LOAD_DYLINKER]
description = "Command to load a specific dynamic linker to bind dylibs into this object"
value = 14
[commands.LC_LOAD_UPWARD_DYLIB]
value = 2147483683
[commands.LC_LOAD_WEAK_DYLIB]
description = "Attempt to load a Dylib but do not fail if binding cannot occur due to its absence"
value = 2147483672
[commands.LC_MAIN]
description = "Mach-O binary entry point"
value = 2147483688
[commands.LC_NOTE]
description = "An arbitrary human readable text note included in this Mach-O.  These should not be used by automated tooling as their unstructured"
value = 49
[commands.LC_PREBIND_CKSUM]
description = "Checksum data to know if this \"optimized\" or prebound object is still valid for the files it was generated from."
value = 23
[commands.LC_PREBOUND_DYLIB]
value = 16
[commands.LC_PREPAGE]
value = 10
[commands.LC_REEXPORT_DYLIB]
description = "Used to export symbols from an object file that this object imported"
value = 2147483679
[commands.LC_ROUTINES]
description = "Used to define initialize / finalize functions on 32bit platforms.  Historical as _init_func/_term_func are now how this is handled."
value = 17
[commands.LC_ROUTINES_64]
description = "Used to define initialize / finalize functions on 64bit platforms.  Historical as _init_func/_term_func are now how this is handled."
value = 26
[commands.LC_RPATH]
value = 2147483676
[commands.LC_SEGMENT]
description = "Causes the loading of a 32bit segment with a given protection level.  Contains 0 or more sections"
value = 1
[commands.LC_SEGMENT_64]
description = "Causes the loading of a 64bit segment with a given protection level.  Contains 0 or more sections"
value = 25
[commands.LC_SEGMENT_SPLIT_INFO]
value = 30
[commands.LC_SOURCE_VERSION]
description = "The verion of source code this Mach-O file was built from"
value = 42
[commands.LC_SUB_CLIENT]
value = 20
[commands.LC_SUB_FRAMEWORK]
description = "Used by \"Umbrella Frameworks\" to declare the frameworks that the umbrella re-exports.  For an example see Cocoa, AppKit and Foundation"
value = 18
[commands.LC_SUB_LIBRARY]
value = 21
[commands.LC_SUB_UMBRELLA]
description = "Used by \"Umbrella Frameworks\" that re-export other frameworks (Cocoa exports Foundation, AppKit for example of this)"
value = 19
[commands.LC_SYMSEG]
description = "Classical GCC compatible \"symbol segment\".  Not commonly used as it is replaced with dyld opcodes."
value = 3
[commands.LC_SYMTAB]
description = "Classical symbol table (direct symbols defined in this object)"
value = 2
[commands.LC_THREAD]
description = "Initial state of the Mach thread for a executable Mach-O"
value = 4
[commands.LC_TWOLEVEL_HINTS]
description = "Two level namespacing allows for the binding to a symbol that may have the same name in two different libraries.  The first namespace is the dylib contining the symbol and the second namespace is the symbol itself."
value = 22
[commands.LC_UNIXTHREAD]
description = "Initial state of the Unix / POSIX thread for an executable Mach-O"
value = 5
[commands.LC_UUID]
description = "A UUID (GUID) that uniquely identifies this object.  Should only occur once"
value = 27
[commands.LC_VERSION_MIN_IPHONEOS]
description = "A declared minimum SDK for iOS"
value = 37
[commands.LC_VERSION_MIN_MACOSX]
description = "A declared minimum SDK for macOS"
value = 36
[commands.LC_VERSION_MIN_TVOS]
description = "The minimum tvOS to load and execute this binary"
value = 47
[commands.LC_VERSION_MIN_WATCHOS]
description = "The minimum watchOS to laod and execute this binary"
value = 48
[file_types.MH_BUNDLE]
description = "A loadable bundle (often essentially a plugin) should be a complete closure on symbols such as a executable but intended to be loaded into another process's virtual memory space.  A reason for the usage of `MH_BUNDLE` is that the object must be explicitly late bound by calling `dlopen` or related APIs, it cannot be linked to as though it were a library."
value = 8
[file_types.MH_CORE]
description = "A core dump (user or kernel)"
value = 4
[file_types.MH_DSYM]
description = "A compile unit containing only debugging symbols"
value = 10
[file_types.MH_DYLIB]
description = "A dynamic (read bound at runtime) library"
value = 6
[file_types.MH_DYLIB_STUB]
description = "An object used for linking that contains no content.  Somewhat similar in nature to a `.tlb` file and no longer in common usage as Apple uses TLB files as a replacement."
value = 9
[file_types.MH_DYLINKER]
description = "A dynamic linker (typically only one exists and is"
value = 7
[file_types.MH_EXECUTE]
description = "A complete executable MachO file (typically a user mode binary)"
value = 2
[file_types.MH_FILESET]
description = "A collection of other MachO files, used by KernelCollections"
value = 12
[file_types.MH_FVMLIB]
description = "A FVM (fixed virtual memory, or non-relocatable/non-position independenct code PIC) dynamic library"
value = 3
[file_types.MH_KEXT_BUNDLE]
description = "A kernel extension bundle.  Name comes from 32bit lineage where MH_BUNDLE were kexts.rake on non-64bit platforms"
value = 11
[file_types.MH_OBJECT]
description = "An intermediate object file that results from a compile unit (e.g. single .c file)"
value = 1
[file_types.MH_PRELOAD]
description = "\\\"Preloaded\\\" images.  Used for firmware payloads"
value = 5
[segments.__AUTH]
description = "Used by arm64e for pointer authenticaton codes (PAC) mutable data"
[segments.__AUTH.__data]
description = "General purpose PAC authenticated data"
[segments.__AUTH.__objc_data]
description = "ObjC specific PAC authenticated data"
[segments.__AUTH_CONST]
description = "Used by arm64e pointer authentication codes (PAC) and read only"
[segments.__AUTH_CONST.__auth_got]
description = "Authenticated Global offset Table"
[segments.__AUTH_CONST.__cfstring]
description = "Authenticated CoreFoundation strings"
[segments.__AUTH_CONST.__const]
description = "Authenticated constants"
[segments.__AUTH_CONST.__got]
description = "Global offset Table"
[segments.__AUTH_CONST.__objc_const]
description = "Authenticated Objective-C constant values"
[segments.__CTF]
description = "Compact C Type Format"
[segments.__CTF.__ctf]
description = "https://github.com/apple-oss-distributions/dtrace/tree/main/tools/ctfconvert"
[segments.__DATA]
description = "Mutable data region (rw-)"
[segments.__DATA.__bss]
description = "Basic initialized data section"
[segments.__DATA.__const]
description = "Constant data, no longer in common usage, see __DATA_CONST.__const"
[segments.__DATA.__data]
description = "General purpose mutable data region"
[segments.__DATA.__got]
description = "Global offset table"
[segments.__DATA.__la_symbol_ptr]
description = "Lazy symbol pointers"
[segments.__DATA.__mod_init_func]
description = "Module initializer function (called at load)"
[segments.__DATA.__mod_term_func]
description = "Module termination function (called at unload)"
[segments.__DATA.__nl_symbol_ptr]
description = "Non-lazy symbol pointers"
[segments.__DATA.__objc_ivar]
description = "ObjC instance variables (ivar)"
[segments.__DATA.__percpu]
description = "Local storage per CPU allowing for lock free globals"
[segments.__DATA_CONST]
description = "Immutable data region (r--)"
[segments.__DATA_CONST.__const]
description = "Constant initialized data"
[segments.__DATA_CONST.__got]
description = "Global offset table"
[segments.__DATA_CONST.__mod_init_func]
description = "Module initializer function"
[segments.__DATA_CONST.__objc_classlist]
description = "List of ObjC classes exported"
[segments.__DATA_CONST.__objc_const]
description = "Constant ObjC data"
[segments.__DATA_CONST.__objc_protolist]
description = "List of ObjC protocols (like interfaces)"
[segments.__HIB]
description = "Hardware specific information for coming out of hibernation.  This section is solely responsable for ensuring that the sleepimage is restored.  Note that it all operates at the same protection levels (code, const, and data) and therefore doesn't take advantage of some hardware protections."
[segments.__HIB.__bootPT]
description = "Initial page table for use during boot up from a hibernation for protected mode"
[segments.__HIB.__bss]
description = "Initialized mutable data"
[segments.__HIB.__const]
description = "Constant data"
[segments.__HIB.__cstring]
description = "C-Style strings for the sleep image restore function"
[segments.__HIB.__data]
description = "General purpose data region for hibernation restore"
[segments.__HIB.__text]
description = "Executable code used to pull a machine out of hibernation"
[segments.__KLD]
description = "The kernel linker (used to dynamiclly bind a kernel extension) analagous to dyld in user-mode"
[segments.__KLD.__text]
description = "The executable code for the kernel linker"
[segments.__KLDDATA]
description = "Data region for KLD or kernel linker"
[segments.__KLDDATA.__bss]
description = "Initialized data"
[segments.__KLDDATA.__const]
description = "Constant data"
[segments.__KLDDATA.__cstring]
description = "C-Style (null terminated) strings for the kernel linker"
[segments.__KLDDATA.__mod_init_func]
description = "Module initializer funtion"
[segments.__KLDDATA.__mod_term_func]
description = "Module termination function"
[segments.__LAST]
description = "Segment that contains the last kernel symbol exported"
[segments.__LAST.__last]
description = "Contains `_last_kernel_symbol` which is the last exported kernel symbol"
[segments.__LASTDATA_CONST]
description = "Last exported symbol from the const region of the kernel or object"
[segments.__LASTDATA_CONST.__mod_init_func]
description = "Module initialization function"
[segments.__LINKEDIT]
description = "Though named \"LINKEDIT\" this segment actually contains any metadata of this Mach-O object.  For example this area contains code signature, as well as dynamic linker opcodes.  This area is always read only.  The contents of this area are described by various `LC_` load commands."
[segments.__OBJC_CONST]
description = "A region of Objective-C metadata that is read-only"
[segments.__OBJC_CONST.__objc_class_ro]
description = "ObjC class info that is read-only to prevent runtime tampering (swizzling for example)"
[segments.__PAGEZERO]
description = "A dummy page used to mark addresses at low memory as not readable.  This causes a dereference of a low integer to cause a page fault helping not propogate type errors when casting pointers."
[segments.__PRELINK_INFO]
description = "Descriptive information about the prelinked region of this object"
[segments.__PRELINK_TEXT]
description = "A region of executable code that is the combination of multiple linkable objects having been prebound"
[segments.__PRELINK_TEXT.__text]
description = "The prelinked, executable code region"
[segments.__TEXT]
description = "The text region contains any executable code (in the machine code of the platform for this binary) and therefore will always be a read-only (write protected) region of memory when mapped into a process.  (r-x)"
[segments.__TEXT.__const]
description = "Constant variables. This region will be non-execute on platforms that support execute never, DEP or NX concepts.  See `__DATA_CONST.__const`"
[segments.__TEXT.__cstring]
description = "ASCII strings null terminated.  This region can be split on `\\0` into strings."
[segments.__TEXT.__eh_frame]
description = "Execption handling frame"
[segments.__TEXT.__gcc_except_tab]
description = "GCC exception handler table"
[segments.__TEXT.__objc_classname]
description = "A collection of strings that provide the names for Objective-C classes in this object file"
[segments.__TEXT.__objc_methname]
description = "A colleciton of strings that provide the names of Objective-C methods for a given class (selectors)"
[segments.__TEXT.__os_log]
description = "Specific support for Apple OSLog facility containing the patterns used"
[segments.__TEXT.__stub_helper]
description = "A helper function that when called binds the prior call site to the proper dyld import"
[segments.__TEXT.__stubs]
description = "Locations that text calls that initially point to a helper thunk (see __stub_helper) but will be late bound to the dynamic symbol"
[segments.__TEXT.__text]
description = "Generic code region.  This area will have the execute flag set on it's content"
[segments.__TEXT.__unwind_info]
description = "Information to help debuggers / exception handlers unwind the stack (info about prolouge etc) allowing for parts of the stack to remain a compiler implementation detail."
[segments.__VECTORS]
description = "Vector table.  Often used to configure a kernel / coprocessor for reset, exception etc.  See ARM-M profile for an example"