
[platforms.audioOS]
architectures = ["arm64","arm64e"]
[platforms.bridgeOS]
architectures = ["arm64"]
[platforms.iOS]
architectures = ["armv6","armv7","arm64","arm64e"]
[platforms.macOS]
archetectures = ["ppc","ppc64","x86","x86_64","x86_64h"]
[platforms.padOS]
architectures = ["armv7","arm64","arm64e"]
[platforms.tvOS]
architectures = ["x86","armv7","arm64","arm64e"]