
[pmu_errors]

[pmu_errors.dbg_rst]
description = "debug based reset"
[pmu_errors.ot]
description = "over-temprature"
[pmu_errors.otp_crc]
description = "one-type-passcode, cyclic redundancy check"
[pmu_errors.ov]
description = "over-voltage"
[pmu_errors.por]
description = "power-on reset"
[pmu_errors.rst]
description = "reset"
[pmu_errors.uv]
description = "under-voltage"
[pmu_errors.wdog]
description = "watchdog timer"