
[[resources]]
title = "Run iOS on QEMU"
type = "article"
url = "https://github.com/alephsecurity/xnu-qemu-arm64/wiki/Build-iOS-on-QEMU"
[[resources]]
title = "onethawt's list of IDA plugins"
type = "article"
url = "https://github.com/onethawt/idaplugins-list"
[[resources]]
title = "Awesome Ghirda Plugins"
type = "article"
url = "https://github.com/AllsafeCyberSecurity/awesome-ghidra"
[[resources]]
title = "USB-C Port Controller (ACE) Secrets"
type = "article"
url = "https://blog.t8012.dev/ace-part-1/"
[[resources]]
title = "Ramtin Amin's Tristar Reverse Engineering"
type = "article"
url = "http://ramtin-amin.fr/#tristar"
[[resources]]
title = "Nyan Satin's Lightning Reverse Engineering"
type = "article"
url = "https://nyansatan.github.io/lightning/"
[[resources]]
title = "http://ramtin-amin.fr/#nvmepcie"
type = "article"
url = "Ramtin Amin's NVMe PCIe Reverse Engineering"
[[resources]]
title = "Ramtin Amin's NVMe DMA Reverse Engineering"
type = "article"
url = "http://ramtin-amin.fr/#nvmedma"
[[resources]]
categories = ["tool","re","ruby"]
description = "FOSS Ruby Mach-O Tool (aims to replicate jtool2 feature set)"
name = "mootool"
type = "repo"
url = "https://github.com/hack-different/mootool"
[[resources]]
categories = ["tool","re","python"]
description = "FOSS Python Mach-O Tool"
name = "ktool"
type = "repo"
url = "https://github.com/cxnder/ktool"
[[resources]]
categories = ["toolchain","c"]
description = "Toolchain used to compile checkra1n and pongoOS"
name = "checkra1n-toolchain"
type = "repo"
url = "https://github.com/checkra1n/toolchain"
[[resources]]
categories = ["emulation","c","xnu"]
description = "QEMU branch for emulating iOS / XNU on arm64"
name = "alephsecurity/xnu-qemu-arm64"
type = "repo"
url = "https://github.com/alephsecurity/xnu-qemu-arm64"
[[resources]]
categories = ["tool","emulation"]
description = "Tooling to prepare an image for QEMU"
name = "alephsecurity/xnu-qemu-arm64-tools"
type = "repo"
url = "https://github.com/alephsecurity/xnu-qemu-arm64-tools"
[[resources]]
categories = ["ida_plugin","disassembly","re"]
description = "IDA plugin for XNU kernelcaches"
name = "cellebrite-srl/ida_kernelcache"
type = "repo"
url = "https://github.com/cellebrite-srl/ida_kernelcache"
[[resources]]
categories = ["ida_plugin","disassembly","re"]
description = "IDA plugin for pointer authentication"
name = "cellebrite-srl/PacExplorer"
type = "repo"
url = "https://github.com/cellebrite-srl/PacXplorer"
[[resources]]
categories = ["ida_plugin","disassembly","re"]
description = "IDA plugin for function inlining"
name = "cellebrite-srl/FunctionInliner"
type = "repo"
url = "https://github.com/cellebrite-srl/FunctionInliner"
[[resources]]
categories = ["ghidra_plugin","disassembly","re"]
description = "Ghidra plugin for XNU kernel caches"
name = "0x36/ghidra_kernelcache"
type = "repo"
url = "https://github.com/0x36/ghidra_kernelcache"
[[resources]]
categories = ["tool"]
description = "Swiss army knife for IPSWs"
name = "blacktop/ipsw"
type = "repo"
url = "https://github.com/blacktop/ipsw"
[[resources]]
name = "pongoOS"
type = "repo"
url = "https://github.com/checkra1n/pongoOS"
[[resources]]
name = "DeMuxUSB - USBMuxD disector"
type = "repo"
url = "https://github.com/t8012/demuxusb"
[[resources]]
name = "open source usbmuxd implementation from libimobiledevice"
type = "repo"
url = "https://github.com/libimobiledevice/usbmuxd"
[[resources]]
name = "libimobiledevice"
type = "repo"
url = "https://github.com/libimobiledevice/libimobiledevice"
[[resources]]
name = "libirecovery - low level iBoot / DFU handler"
type = "repo"
url = "https://github.com/libimobiledevice/libirecovery"
[[resources]]
name = "idevicerestore - open source Apple device restore tool"
type = "repo"
url = "https://github.com/libimobiledevice/idevicerestore"
[[resources]]
name = "UTDM - USB Target Disk Mode"
type = "repo"
url = "https://github.com/rickmark/apple_utdm"
[[resources]]
name = "MacVDMTool and Library - USB-PD Vendor Defined Messsages"
type = "repo"
url = "https://github.com/rickmark/macvdmtool"
[[resources]]
name = "Apple Remote Virtaul Interface"
type = "repo"
url = "https://github.com/gh2o/rvi_capture"
[[resources]]
name = "Thunderbolt Patcher by osy"
type = "repo"
url = "https://github.com/osy/ThunderboltPatcher"
[[resources]]
name = "Apple Wireless Diagnostics logging decode"
type = "repo"
url = "https://github.com/rickmark/awdd_decode"
[[resources]]
name = "Shareport - AirPlay2 implementation"
type = "repo"
url = "https://github.com/mikebrady/shairport-sync"
[[resources]]
name = "open source iOS backup library"
type = "repo"
url = "https://github.com/rickmark/libibackup"
[[resources]]
name = "BOM - Bill of Materials by NeXT / Apple"
type = "repo"
url = "https://github.com/iineva/bom"
[[resources]]
name = "Open source plist implementation"
type = "repo"
url = "https://github.com/libimobiledevice/libplist"
[[resources]]
name = "Open Source iTunes Library Parser"
type = "repo"
url = "https://github.com/josephw/titl"
[[resources]]
name = "SBinger's fork of the ldid link editor"
type = "repo"
url = "https://github.com/sbingner/ldid"
[[resources]]
name = "T1 and prior EFI firmware verification"
type = "repo"
url = "https://github.com/t8012/efivalidate"
[[resources]]
name = "List of all SecureROM / SEPROMs"
type = "repo"
url = "https://github.com/hekapooios/hekapooios.github.io"
[[resources]]
name = "Apple WiFi Password Sharing Implementation"
type = "repo"
url = "https://github.com/seemoo-lab/openwifipass"
[[resources]]
name = "Create SMC binaries from update payloads"
type = "repo"
url = "https://github.com/t8012/smcutil"
[[resources]]
name = "Virtual SMC implementation for Clover"
type = "repo"
url = "https://github.com/acidanthera/VirtualSMC"
[[resources]]
name = "IDA - The Intellegent Disassembler"
type = "tool"
url = "https://hex-rays.com/ida-pro/"
[[resources]]
name = "VisUAL ARM Simulator"
type = "tool"
url = "https://salmanarif.bitbucket.io/visual/index.html"
[[resources]]
name = "Ghidra Disassembler"
open_source = true
type = "tool"
url = "https://ghidra-sre.org"
[[resources]]
name = "Hopper Disassembler"
type = "tool"
url = "https://www.hopperapp.com"
[[resources]]
name = "jtool2 by Levin"
type = "tool"
url = "https://www.newosxbook.com/tools/jtool.html"
[[resources]]
name = "Frida - Dynamic instrumentation toolkit for developers"
open_source = true
type = "tool"
url = "https://frida.re/"
[[resources]]
name = "libimobiledevice - open source Apple / iTunes implementation"
type = "tool"
url = "https://libimobiledevice.org"
[[resources]]
title = "Apple - Kernel Programming Guide"
type = "article"
url = "https://developer.apple.com/library/content/documentation/Darwin/Conceptual/KernelProgramming"
[[resources]]
title = "Apple - IOKit Fundamentals"
type = "article"
url = "https://developer.apple.com/library/content/documentation/DeviceDrivers/Conceptual/IOKitFundamentals"
[[resources]]
title = "Apple - Virtual Memory System"
type = "article"
url = "https://developer.apple.com/library/content/documentation/Performance/Conceptual/ManagingMemory/Articles/AboutMemory.html"