
[launchd_services]

[launchd_services.com.apple.ABDatabaseDoctor]
description = "AddressBook database repair"
[launchd_services.com.apple.AdminLite]
binary = "/System/Library/PrivateFrameworks/AdminLite.framework/Resources/AdminLiteTool"
description = "Turns on / off setting boot-args"
[launchd_services.com.apple.AppleSSODaemon]
description = "Apple ID"
[launchd_services.com.apple.BTServer.avrcp]
description = "Bluetooth Audio/Video Remote Control Profile (AVRCP)"
[launchd_services.com.apple.BTServer.cloudpairing]
description = "iCloud Pairing for AirPods etc."
[launchd_services.com.apple.BTServer.map]
description = "Bluetooth Message Access Profile (MAP)"
[launchd_services.com.apple.BTServer.pbap]
description = "Bluetooth Phone Book Access Profile (PBAP)"
[launchd_services.com.apple.BarcodeSupport.BarcodeNotificationService]
description = "Camera QR code reader"
[launchd_services.com.apple.CarPlayApp]
platforms = ["iOS"]
[launchd_services.com.apple.CommCenter]
description = "Deal with the radios"
[launchd_services.com.apple.CoreAuthentication.agent]
binary = "/System/Library/Frameworks/LocalAuthentication.framework/Support/coreauthd"
description = "coreauthd is a system daemon or agent that provides LocalAuthentication services. It maintains the authenticated contexts and presents the authentication user interface."
[launchd_services.com.apple.CoreRoutine.helperservice]
binary = "/System/Library/PrivateFrameworks/CoreRoutine.framework/Versions/A/XPCServices/CoreRoutineHelperService.xpc/Contents/MacOS/CoreRoutineHelperService"
endpoints = ["com.apple.CoreRoutine.helperservice"]
platforms = ["macOS Intel"]
[launchd_services.com.apple.DataDetectorsSourceAccess]
description = "Find phone numbers, shipping tracking codes"
[launchd_services.com.apple.DumpBasebandCrash]
description = "Collect logs from the Baseband if it crashes"
[launchd_services.com.apple.DumpPanic]
description = "Reads kernel panics from block storage and writes to log"
[launchd_services.com.apple.MobileAccessoryUpdater]
description = "Update attached accessories like [[Haywire]]"
[launchd_services.com.apple.ProxiedCrashCopier.ProxyingDevice]
description = "move crash logs, awdd and sysdiagnose from the watch to the phone"
[launchd_services.com.apple.SCHelper]
description = "Smart Card helper"
platforms = ["macOS"]
[launchd_services.com.apple.SpringBoard]
platforms = ["iOS"]
[launchd_services.com.apple.TrustEvaluationAgent]
binary = "/System/Library/PrivateFrameworks/TrustEvaluationAgent.framework/Resources/trustevaluationagent"
platforms = ["macOS Intel"]
[launchd_services.com.apple.TrustedPeersHelper]
binary = "/System/Library/Frameworks/Security.framework/Versions/A/XPCServices/TrustedPeersHelper.xpc/Contents/MacOS/TrustedPeersHelper"
[launchd_services.com.apple.VoiceOverTouch]
description = "VoiceOver or the reading of the UI to the user"
[launchd_services.com.apple.accessibility.heard]
description = "Hearing aid"
[launchd_services.com.apple.accessoryd]
description = "iAP or Apple Accessory Protocol - Handle accessories via USB / Lightning"
platforms = ["iOS","padOS"]
[launchd_services.com.apple.adid]
binary = "/usr/libexec/adid"
[launchd_services.com.apple.afcd]
binary = "/usr/libexec/afcd"
[launchd_services.com.apple.aggregated]
description = "Create aggregate logs"
[launchd_services.com.apple.airtunesd]
binary = "/usr/libexec/airtunesd"
description = "iTunes library sharing"
[launchd_services.com.apple.akd]
description = "AuthKit"
[launchd_services.com.apple.ap.adprivacyd]
binary = "/usr/libexec/adprivacyd"
description = "iAd privacy"
[launchd_services.com.apple.ap.adservicesd]
binary = "/usr/libexec/adservicesd"
description = "iAd services"
[launchd_services.com.apple.applecamerad]
binary = "/usr/libexec/adservicesd"
description = "Camera handler"
[launchd_services.com.apple.appstored]
description = "App Store"
[launchd_services.com.apple.asd]
binary = "/usr/libexec/asd"
[launchd_services.com.apple.aslmanager]
description = "Apple System Log"
[launchd_services.com.apple.atc]
binary = "/usr/libexec/atc"
[launchd_services.com.apple.atc.atwakeup]
binary = "/usr/libexec/atwakeup"
[launchd_services.com.apple.avatarsd]
description = "iMessage / iCloud profile photos"
[launchd_services.com.apple.awdd]
description = "Apple Wireless Diagnostics Daemon"
[launchd_services.com.apple.backboardd]
binary = "/usr/libexec/backboardd"
[launchd_services.com.apple.biometrickitd.pearl]
description = "FaceID"
[launchd_services.com.apple.bird]
description = "iCloud Documents / Ubiquity Containers"
[launchd_services.com.apple.bluetoothd]
description = "Bluetooth"
[launchd_services.com.apple.captiveagent]
description = "Handle captive WiFi login"
[launchd_services.com.apple.cfnetwork.cfnetworkagent]
description = "Core Foundation networking"
[launchd_services.com.apple.cfprefsd.xpc.daemon]
description = "Core Foundation preference sync"
[launchd_services.com.apple.cloudd]
description = "iCloud"
[launchd_services.com.apple.cloudphotod]
description = "iCloud photo library"
[launchd_services.com.apple.configd]
binary = "/usr/libexec/configd"
[launchd_services.com.apple.contacts.donation-agent]
description = "Provide contacts from a sync provider"
[launchd_services.com.apple.contactsd]
description = "Contacts handler"
[launchd_services.com.apple.containermanagerd]
description = "Mange App and Group containers"
[launchd_services.com.apple.corecaptured]
description = "WiFi / Bluetooth diagnostic capture"
[launchd_services.com.apple.coreidvd]
binary = "/usr/libexec/coreidvd"
description = "Daemon for the CoreIDV private framework (probably \"identity verification\" for Apple Pay)"
[launchd_services.com.apple.ctkd]
description = "Cloud Token Kit daemon"
[launchd_services.com.apple.dasd]
binary = "/usr/libexec/dasd"
description = "Duet Activity Scheduler Daemon (related to DuetActivityScheduler.framework)"
[launchd_services.com.apple.datamigrator]
description = "Handles data conversion after OS update"
[launchd_services.com.apple.device-o-matic]
description = "Figure out what profile to present when the device is connected via USB"
[launchd_services.com.apple.diagnosticd]
description = "Diagnostics"
[launchd_services.com.apple.diagnosticextensionsd]
description = "Manage diagnostic extensions"
[launchd_services.com.apple.distnoted.xpc.agent]
binary = "/usr/sbin/distnoted"
[launchd_services.com.apple.distnoted.xpc.daemon]
description = "Distributed notificaions"
[launchd_services.com.apple.dprivacyd]
description = "Differential Privacy"
[launchd_services.com.apple.email.maild]
description = "Email daemon for background push"
[launchd_services.com.apple.exchangesyncd]
description = "Exchange mail/contacts handler"
[launchd_services.com.apple.facebook.xpc]
description = "Facebook account handler"
[launchd_services.com.apple.fairplay.H2]
danger = true
description = "FairPlay is the DRM (digital rights management) system for Apple - research in this area is dangorous"
[launchd_services.com.apple.familycircled]
description = "iCloud Family Management"
[launchd_services.com.apple.familynotificaiton]
description = "Notify UI for family events"
[launchd_services.com.apple.fdrhelper]
binary = "/usr/libexec/fdrhelper"
description = "Factory Data Reset"
[launchd_services.com.apple.filesystems.apfs_defragd]
description = "online defragment and optimize for APFS"
[launchd_services.com.apple.filesystems.livefileproviderd]
description = "Files.app service"
[launchd_services.com.apple.filesystems.smbclientd]
description = "Server Message Block client"
[launchd_services.com.apple.fseventsd]
description = "Filesystem events"
[launchd_services.com.apple.gamed]
description = "GameKit"
[launchd_services.com.apple.geod]
binary = "/System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/XPCServices/com.apple.geod.xpc/Contents/MacOS/com.apple.geod"
description = "Geo-fencing"
platforms = ["macOS Intel"]
[launchd_services.com.apple.gpsd]
description = "GPS"
[launchd_services.com.apple.handwritingd]
description = "iPad Handwriting Recogntion"
[launchd_services.com.apple.healthappd]
description = "Health App"
[launchd_services.com.apple.healthd]
description = "HealthKit"
[launchd_services.com.apple.homed]
description = "HomeKit"
[launchd_services.com.apple.iapauthd]
description = "iAccessory authentication"
[launchd_services.com.apple.iapd]
description = "iAccessory Protocol handler"
[launchd_services.com.apple.icloud.findmydeviced]
description = "Find my iPhone"
[launchd_services.com.apple.icloud.fmfd]
description = "Find my friends"
[launchd_services.com.apple.icloud.fmflocatord]
description = "Find my friends"
[launchd_services.com.apple.icloud.searchpartyd]
description = "The searching component looking for offline devices broadcasging for FindMy and sending to Apple"
[launchd_services.com.apple.idamd]
binary = "/usr/libexec/idamd"
[launchd_services.com.apple.idsfoundation.IDSRemoteURLConnectionAgent]
description = "Make URL requests under identity services without exposing credential"
[launchd_services.com.apple.imagent]
description = "Instant Message Agent (iMessage)"
[launchd_services.com.apple.imcore.imtransferagent]
description = "iMessage attachment handler"
[launchd_services.com.apple.locationd]
description = "Location services"
[launchd_services.com.apple.logd]
description = "Logging Daemon"
[launchd_services.com.apple.lsd]
description = "Launch Services daemon"
[launchd_services.com.apple.lskdd]
binary = "/usr/libexec/lskdd"
description = "Local System Kernel Debug Daemon?"
[launchd_services.com.apple.lskdmsed]
binary = "/usr/libexec/lskdmsed"
description = "Local System Kernel Debug Memory Daemon?"
[launchd_services.com.apple.managedconfiguration.mdmd]
description = "Mobile Device Manager daemon"
[launchd_services.com.apple.managedconfiguration.passscodenagd]
description = "Tells you to set a passcode if set from policy"
[launchd_services.com.apple.managedconfiguration.profiled]
description = ".mobileprofile management"
[launchd_services.com.apple.mediaartworkd]
description = "iTunes Cover Art"
[launchd_services.com.apple.migrationpluginwrapper]
description = "Environment for OS upgrade migration plugins to run in"
[launchd_services.com.apple.misagent]
binary = "/usr/libexec/misagent"
description = "Provisioning profiles"
[launchd_services.com.apple.mlmodelingd]
description = "Machine Learning modeling daemon"
[launchd_services.com.apple.mobile.MCInstall]
description = ".mobileconfig management"
[launchd_services.com.apple.mobile.obliteration]
description = "Erase device via AppleEffacableStorage"
[launchd_services.com.apple.mobilegestalt.xpc]
description = "Get device properties like model / serial"
[launchd_services.com.apple.monbile.house_arrest]
description = "iTunes file transfer for application documents"
[launchd_services.com.apple.nanobackupd]
description = "Apple Watch backup agent"
[launchd_services.com.apple.nanoprefsyncd.2]
description = "Apple Watch preference syncing"
[launchd_services.com.apple.nanoregistryd]
description = "Apple Watch application registry (launch services)"
[launchd_services.com.apple.nanosubridged]
description = "Apple Watch Software Update Bridge"
[launchd_services.com.apple.neagent-ios]
binary = "/usr/libexec/neagent"
description = "Network Extension - Agent"
[launchd_services.com.apple.nearbyd]
binary = "/usr/libexec/nearbyd"
[launchd_services.com.apple.nehelper]
binary = "/usr/libexec/nehelper"
description = "Network Extensions"
[launchd_services.com.apple.nesessionmanager]
binary = "/usr/libexec/nesessionmanager"
[launchd_services.com.apple.networkserviceproxy]
binary = "/usr/libexec/networkserviceproxy"
[launchd_services.com.apple.newsd]
description = "Apple News"
[launchd_services.com.apple.nfcd]
binary = "/usr/libexec/nfcd"
description = "Near Field Communications"
[launchd_services.com.apple.nfrestore]
binary = "/usr/libexec/nfrestore_service"
[launchd_services.com.apple.nlcd]
binary = "/usr/libexec/ncld"
description = "Network Link Conditioner"
[launchd_services.com.apple.passd]
description = "Passbook"
[launchd_services.com.apple.pasteboard.pasted]
description = "Clipboard / Paseboard Services"
[launchd_services.com.apple.pcapd]
binary = "/usr/libexec/pcapd"
description = "Packet Capture"
[launchd_services.com.apple.pfd]
binary = "/usr/libexec/pfd"
description = "Packet Filter"
[launchd_services.com.apple.pluginkit.pkd]
binary = "/usr/libexec/pkd"
description = "pkd manages plug-ins for the PlugInKit subsystem. It is a classic launch agent managed by launchd."
endpoints = ["com.apple.pluginkit.pkd"]
platforms = ["macOS Intel"]
[launchd_services.com.apple.preboardservice]
description = "First unlock screen"
[launchd_services.com.apple.ptpcamerad]
description = "Picture Transfer Protocol"
[launchd_services.com.apple.ptpd]
description = "Picture Transfer Protocol"
[launchd_services.com.apple.racoon]
description = "VPN"
[launchd_services.com.apple.recentsd]
description = "Most recently used (MRU) list"
[launchd_services.com.apple.replayd]
description = "Game Kit instant replay"
[launchd_services.com.apple.reversetimplated]
description = "Create user folder layout from template"
[launchd_services.com.apple.revisiond]
description = "Historical file revision management"
[launchd_services.com.apple.screensharingserver]
description = "AirPlay"
[launchd_services.com.apple.searchd]
description = "Spotlight"
[launchd_services.com.apple.security.XPCTimeStampingService]
binary = "/System/Library/Frameworks/Security.framework/Versions/A/XPCServices/XPCTimeStampingService.xpc/Contents/MacOS/XPCTimeStampingService"
[launchd_services.com.apple.securityd]
binary = "/usr/libexec/securityd"
description = "Handle keychains etc"
[launchd_services.com.apple.securityuploadd]
binary = "/usr/libexec/securityuploadd"
[launchd_services.com.apple.seld]
binary = "/usr/libexec/seld"
[launchd_services.com.apple.sensorkitd]
binary = "/usr/libexec/sensorkitd"
[launchd_services.com.apple.seserviced]
binary = "/usr/libexec/seserviced"
description = "Secure Element interface"
[launchd_services.com.apple.sharingd]
binary = "/usr/libexec/sharingd"
description = "Generic \"Share\" action handler"
[launchd_services.com.apple.sidecar-relay]
binary = "/usr/libexec/SidecarRelay"
description = "Use iDevice as a screen"
[launchd_services.com.apple.signpost.signpost_reporter]
binary = "/usr/libexec/signpost_reporter"
[launchd_services.com.apple.sosd]
description = "Emergency recovery for iCloud Keychain"
[launchd_services.com.apple.streaming_zip_conduit]
binary = "/usr/libexec/streaming_zip_conduit"
description = "Handle untrusted Zip content out of process"
[launchd_services.com.apple.swcd]
binary = "/usr/libexec/swcd"
description = "Shared Web Credentials"
[launchd_services.com.apple.tailspind]
binary = "/usr/libexec/tailspind"
[launchd_services.com.apple.tccd]
description = "Total and Complete Control - App privacy settings"
[launchd_services.com.apple.terminusd]
binary = "/usr/libexec/terminusd"
description = "On-demand VPN"
[launchd_services.com.apple.thermalmonitord]
binary = "/usr/libexec/thermalmonitord"
[launchd_services.com.apple.timed]
binary = "/usr/libexec/timed"
description = "NTP Client"
[launchd_services.com.apple.timezoneupdates.tzd]
binary = "/usr/libexec/tzd"
[launchd_services.com.apple.tipsd]
binary = "/usr/libexec/tipsd"
description = "Tip of the day"
[launchd_services.com.apple.tonelibraryd]
description = "Ringtone library access"
[launchd_services.com.apple.transparencyd]
binary = "/usr/libexec/transparencyd"
[launchd_services.com.apple.triald]
binary = "/usr/libexec/triald"
description = "Apple A/B testing"
[launchd_services.com.apple.trustd]
binary = "/usr/libexec/trustd"
description = "PKI trust evaluation"
[launchd_services.com.apple.tvremoted]
description = "Apple TV remote app"
[launchd_services.com.apple.twitter.xpc]
description = "Twitter account handler"
[launchd_services.com.apple.tzlinkd]
binary = "/usr/libexec/tzlinkd"
description = "Time Zones"
[launchd_services.com.apple.videosybscriptionsd]
binary = "/usr/libexec/videosubscriptionsd"
[launchd_services.com.apple.voicememod]
description = "Voice Memos"
[launchd_services.com.apple.watchdogd]
binary = "/usr/libexec/watchdogd"
[launchd_services.com.apple.wcd]
binary = "/usr/libexec/wcd"
[launchd_services.com.apple.webinspectord]
binary = "/usr/libexec/webinspectord"
[launchd_services.com.apple.webio.xpc]
description = "Webio account handler"
[launchd_services.com.apple.wifi.hostapd]
description = "Host Access Point - Instant Hotspot"
[launchd_services.com.apple.wifi.wapic]
binary = "/usr/libexec/wapic"
[launchd_services.com.apple.wifiFirmwareLoader]
binary = "/usr/libexec/wifiFirmwareLoader"
description = "Move the firmware from disk to the WiFi chip"
[launchd_services.com.apple.wifianalyticsd]
binary = "/usr/libexec/wifianalyticsd"
[launchd_services.com.apple.wifid]
description = "WiFi"
[launchd_services.com.apple.wifip2pd]
binary = "/usr/libexec/wifip2pd"
description = "WiFi peer-to-peer"
[launchd_services.com.apple.wifivelocityd]
binary = "/usr/libexec/wifivelocityd"
[launchd_services.com.apple.xpc.roleaccountd]
binary = "/usr/libexec/xpcroleaccountd"